"""Agent integrations: one MCP server + generated instructions, per detected agent.

Every write is idempotent and reversible: JSON configs are merged key-by-key, Markdown files get a
marked block, and generated files carry a header so `cairn uninstall` removes exactly what it added.
"""
from __future__ import annotations

import json
import shutil
import subprocess
import sys
from pathlib import Path

from .project import Project

TEMPLATES = Path(__file__).resolve().parent / "templates"
BEGIN, END = "<!-- cairn:begin -->", "<!-- cairn:end -->"
GENERATED = "<!-- generated by cairn; safe to edit, removed by `cairn uninstall` -->"

AGENTS = {
    "claude": "Claude Code",
    "codex": "Codex",
    "cursor": "Cursor",
    "gemini": "Gemini CLI",
    "vscode": "VS Code / Copilot",
}


def command() -> tuple[str, list[str]]:
    """How agents launch the MCP server. Prefer the portable `cairn` on PATH."""
    if shutil.which("cairn"):
        return "cairn", ["mcp"]
    return sys.executable, ["-m", "cairn", "mcp"]


def detect(project: Project) -> list[str]:
    home, root = Path.home(), project.root
    found = []
    checks = {
        "claude": [shutil.which("claude"), (home / ".claude").is_dir(), (root / ".claude").is_dir(), (root / "CLAUDE.md").exists()],
        "codex": [shutil.which("codex"), (home / ".codex").is_dir()],
        "cursor": [shutil.which("cursor"), (home / ".cursor").is_dir(), (root / ".cursor").is_dir()],
        "gemini": [shutil.which("gemini"), (home / ".gemini").is_dir(), (root / "GEMINI.md").exists()],
        "vscode": [shutil.which("code"), (root / ".vscode").is_dir()],
    }
    for name, signals in checks.items():
        if any(signals):
            found.append(name)
    return found


# ---- file helpers ------------------------------------------------------------------------------------
def upsert_block(path: Path, body: str) -> bool:
    text = path.read_text() if path.exists() else ""
    block = f"{BEGIN}\n{body.strip()}\n{END}"
    if BEGIN in text and END in text:
        new = text[: text.index(BEGIN)] + block + text[text.index(END) + len(END):]
    else:
        new = (text.rstrip() + "\n\n" if text.strip() else "") + block + "\n"
    if new != text:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(new)
        return True
    return False


def remove_block(path: Path) -> bool:
    if not path.exists():
        return False
    text = path.read_text()
    if BEGIN not in text:
        return False
    new = (text[: text.index(BEGIN)] + text[text.index(END) + len(END):]).strip()
    if new:
        path.write_text(new + "\n")
    else:
        path.unlink()
    return True


def merge_json(path: Path, mutate) -> bool:
    try:
        data = json.loads(path.read_text()) if path.exists() else {}
    except json.JSONDecodeError:
        return False  # never clobber a file we cannot parse
    before = json.dumps(data, sort_keys=True)
    mutate(data)
    if json.dumps(data, sort_keys=True) != before:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(json.dumps(data, indent=2) + "\n")
        return True
    return False


def write_generated(path: Path, content: str) -> bool:
    if path.exists() and GENERATED not in path.read_text():
        return False  # user-owned file with the same name: leave it
    parts = content.split("---", 2)
    if content.startswith("---") and len(parts) == 3:  # keep frontmatter first
        content = f"---{parts[1]}---\n{GENERATED}{parts[2]}"
    else:
        content = f"{GENERATED}\n{content}"
    if path.exists() and path.read_text() == content:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    return True


def _hook_cmd(event: str) -> str:
    return f"cairn hook {event}" if shutil.which("cairn") else f'"{sys.executable}" -m cairn hook {event}'


# ---- installers --------------------------------------------------------------------------------------
def install(project: Project, agents: list[str] | None = None) -> dict[str, list[str]]:
    agents = agents or detect(project)
    root = project.root
    cmd, args = command()
    instructions = (TEMPLATES / "instructions.md").read_text()
    changed: dict[str, list[str]] = {}

    def note(agent, path, did):
        if did:
            changed.setdefault(agent, []).append(str(Path(path).relative_to(root)) if str(path).startswith(str(root)) else str(path))

    note("generic", root / "AGENTS.md", upsert_block(root / "AGENTS.md", instructions))
    if "claude" in agents:
        note("claude", root / ".mcp.json", merge_json(root / ".mcp.json", lambda d: d.setdefault("mcpServers", {})
                                                        .update({"cairn": {"command": cmd, "args": args}})))

        def settings(d):
            hooks = d.setdefault("hooks", {})
            ss = hooks.setdefault("SessionStart", [])
            if not any("cairn hook session-start" in json.dumps(h) for h in ss):
                ss.append({"hooks": [{"type": "command", "command": _hook_cmd("session-start")}]})
            d.setdefault("statusLine", {"type": "command", "command": _hook_cmd("statusline").replace(
                "hook statusline", "statusline"), "padding": 0})
            perms = d.setdefault("permissions", {}).setdefault("allow", [])
            if "mcp__cairn" not in perms:
                perms.append("mcp__cairn")
        note("claude", root / ".claude/settings.json", merge_json(root / ".claude" / "settings.json", settings))
        for f in (TEMPLATES / "claude" / "commands").glob("*.md"):
            p = root / ".claude" / "commands" / "cairn" / f.name
            note("claude", p, write_generated(p, f.read_text()))
        for f in (TEMPLATES / "claude" / "agents").glob("*.md"):
            p = root / ".claude" / "agents" / f.name
            note("claude", p, write_generated(p, f.read_text()))
        note("claude", root / "CLAUDE.md", upsert_block(root / "CLAUDE.md", instructions))
    if "cursor" in agents:
        note("cursor", root / ".cursor/mcp.json", merge_json(root / ".cursor" / "mcp.json", lambda d: d.setdefault(
            "mcpServers", {}).update({"cairn": {"command": cmd, "args": args}})))
        rule = "---\ndescription: Cairn project memory\nalwaysApply: true\n---\n" + instructions
        p = root / ".cursor" / "rules" / "cairn.mdc"
        note("cursor", p, write_generated(p, rule))
    if "gemini" in agents:
        note("gemini", root / ".gemini/settings.json", merge_json(root / ".gemini" / "settings.json", lambda d: d.setdefault(
            "mcpServers", {}).update({"cairn": {"command": cmd, "args": args}})))
        note("gemini", root / "GEMINI.md", upsert_block(root / "GEMINI.md", instructions))
    if "vscode" in agents:
        note("vscode", root / ".vscode/mcp.json", merge_json(root / ".vscode" / "mcp.json", lambda d: d.setdefault(
            "servers", {}).update({"cairn": {"type": "stdio", "command": cmd, "args": args}})))
    if "codex" in agents and shutil.which("codex"):
        try:
            listed = subprocess.run(["codex", "mcp", "list"], capture_output=True, text=True, timeout=20).stdout
            if "cairn" not in listed:
                subprocess.run(["codex", "mcp", "add", "cairn", "--", cmd, *args], capture_output=True, timeout=30)
                changed.setdefault("codex", []).append("codex mcp add cairn")
        except (OSError, subprocess.TimeoutExpired):
            pass
    return changed


def uninstall(project: Project) -> list[str]:
    root, removed = project.root, []
    for md in ("AGENTS.md", "CLAUDE.md", "GEMINI.md"):
        if remove_block(root / md):
            removed.append(md)
    for rel, key in ((".mcp.json", "mcpServers"), (".cursor/mcp.json", "mcpServers"),
                     (".gemini/settings.json", "mcpServers"), (".vscode/mcp.json", "servers")):
        if merge_json(root / rel, lambda d, k=key: d.get(k, {}).pop("cairn", None)):
            removed.append(rel)

    def clean(d):
        ss = d.get("hooks", {}).get("SessionStart", [])
        d.get("hooks", {})["SessionStart"] = [h for h in ss if "cairn" not in json.dumps(h)]
        if not d.get("hooks", {}).get("SessionStart"):
            d.get("hooks", {}).pop("SessionStart", None)
        if "cairn" in json.dumps(d.get("statusLine", {})):
            d.pop("statusLine")
        allow = d.get("permissions", {}).get("allow", [])
        if "mcp__cairn" in allow:
            allow.remove("mcp__cairn")
    if merge_json(root / ".claude" / "settings.json", clean):
        removed.append(".claude/settings.json")
    for p in [*(root / ".claude" / "commands" / "cairn").glob("*.md"), *(root / ".claude" / "agents").glob("cairn-*.md"),
              root / ".cursor" / "rules" / "cairn.mdc"]:
        if p.exists() and GENERATED in p.read_text():
            p.unlink()
            removed.append(str(p.relative_to(root)))
    if shutil.which("codex"):
        subprocess.run(["codex", "mcp", "remove", "cairn"], capture_output=True, timeout=30)
    return removed
