"""Regenerate every copy of the diagram tokens from the canonical file.

Canonical: src/cairn/system/diagram/tokens.json. Generated: docs/diagram-standard/tokens.json and the diagram
colour roles block in src/cairn/ui/styles/tokens.css. Run after editing the canonical file; the test suite
fails when a generated copy is out of date (tests/system/test_tokens.py).
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
CANON = ROOT / "src/cairn/system/diagram/tokens.json"
DOCS = ROOT / "docs/diagram-standard/tokens.json"
CSS = ROOT / "src/cairn/ui/styles/tokens.css"
BEGIN, END = "/* diagram roles: generated by scripts/sync_tokens.py, do not edit */", "/* end diagram roles */"


def css_block(tokens: dict) -> str:
    def roles(theme: dict) -> str:
        return "".join(f"  --dg-{k.replace('_', '-')}: {v};\n" for k, v in theme.items())
    light, dark = tokens["themes"]["light"], tokens["themes"]["dark"]
    return (f"{BEGIN}\n:root {{\n{roles(light)}}}\n"
            f"@media (prefers-color-scheme: dark) {{ :root:not([data-theme=light]) {{\n{roles(dark)}}} }}\n"
            f":root[data-theme=dark] {{\n{roles(dark)}}}\n{END}\n")


def render() -> dict[Path, str]:
    tokens = json.loads(CANON.read_text(encoding="utf-8"))
    out = {DOCS: json.dumps(tokens, indent=2, ensure_ascii=False) + "\n"}
    css = CSS.read_text(encoding="utf-8")
    block = css_block(tokens)
    if BEGIN in css:
        css = css[: css.index(BEGIN)] + block + css[css.index(END) + len(END) + 1:]
    else:
        css = css.rstrip("\n") + "\n\n" + block
    out[CSS] = css
    return out


def main(check: bool = False) -> int:
    stale = []
    for path, text in render().items():
        if path.read_text(encoding="utf-8") != text:
            stale.append(path)
            if not check:
                path.write_text(text, encoding="utf-8", newline="\n")
    if check and stale:
        print("out of date:", ", ".join(str(p.relative_to(ROOT)) for p in stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(check="--check" in sys.argv))
