"""Requirement -> test traceability for specs/002-system-model.

Reads every FR-xxx and SC-xxx id from the spec, finds tests whose docstring names the id, writes
specs/002-system-model/traceability.md, and exits 1 (``--check``) when a requirement has no test.
Ids that cannot be tested automatically are listed in MANUAL with the reason; they are reported, not hidden.
"""
from __future__ import annotations

import ast
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SPEC = ROOT / "specs/002-system-model/spec.md"
OUT = ROOT / "specs/002-system-model/traceability.md"
TESTS = ROOT / "tests"
ID = re.compile(r"\b(FR-\d{3}[a-z]?|SC-\d{3}|US\d-AS\d)\b")
MANUAL = {"SC-005": "moderated new-joiner study with at least five people (task T047); cannot run in CI"}


def requirements() -> dict[str, str]:
    """FR and SC ids, plus acceptance scenarios as US<story>-AS<n> in the order the spec lists them."""
    out: dict[str, str] = {}
    story = None
    in_acceptance = False
    for line in SPEC.read_text(encoding="utf-8").splitlines():
        s = line.strip()
        m = re.match(r"^- \*\*((?:FR|SC)-\d{3}[a-z]?)\*\*:\s*(.*)", s)
        if m:
            out[m.group(1)] = m.group(2)[:110]
            continue
        sm = re.match(r"^### User Story (\d+)", s)
        if sm:
            story, in_acceptance = sm.group(1), False
            continue
        if s.startswith("**Acceptance Scenarios**"):
            in_acceptance = story is not None
            continue
        if s.startswith("#") or s.startswith("**Why") or s.startswith("---"):
            in_acceptance = False
        am = re.match(r"^(\d+)\.\s+\*\*Given\*\*(.*)", s)
        if in_acceptance and am:
            out[f"US{story}-AS{am.group(1)}"] = ("Given" + am.group(2))[:110]
    return out


def tests_by_id() -> dict[str, list[str]]:
    found: dict[str, list[str]] = {}
    for path in sorted(TESTS.rglob("test_*.py")):
        try:
            tree = ast.parse(path.read_text(encoding="utf-8"))
        except SyntaxError:
            continue
        rel = path.relative_to(ROOT).as_posix()
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) and node.name.startswith("test_"):
                for rid in set(ID.findall(ast.get_docstring(node) or "")):
                    found.setdefault(rid, []).append(f"{rel}::{node.name}")
    return found


def main(check: bool) -> int:
    reqs, found = requirements(), tests_by_id()
    lines = ["# Traceability: requirement -> tests", "",
             "Generated by `scripts/traceability.py` from test docstrings. The suite fails when a requirement has no test.",
             "", "| Requirement | Tests | Count |", "|---|---|---|"]
    missing = []
    for rid in sorted(reqs, key=lambda x: (x[:2], [int(n) for n in re.findall(r"\d+", x)], x)):
        tests = found.get(rid, [])
        if not tests and rid in MANUAL:
            cell = f"manual: {MANUAL[rid]}"
        elif not tests:
            cell = "**MISSING**"
            missing.append(rid)
        else:
            cell = "<br>".join(f"`{t}`" for t in tests[:6]) + (f" (+{len(tests) - 6} more)" if len(tests) > 6 else "")
        lines.append(f"| {rid} | {cell} | {len(tests)} |")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    if missing:
        print("requirements without tests:", ", ".join(missing))
    return 1 if (check and missing) else 0


if __name__ == "__main__":
    sys.exit(main("--check" in sys.argv))
